# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_variables:
  from9: &from10 gcr.io/google-appengine/debian10:latest
  nuclio: &nuclio
    version: '1.6.11'
versions:
  - dir: 'nuclio_builder'
    repo: nuclio_builder
    templateSubDir: nuclio_builder
    tags: [ 'latest' ]
    builder: true
    packages:
      nuclio: *nuclio
  - repo: nuclio-controller
    builderImage: 'nuclio_builder:latest'
    builderArgs: [ 'controller' ]
    imageNameFromBuilder: 'local/controller:1.6.11'
    tags:
      - '1.6.11-debian9'
      - '1.6-debian9'
      - '1-debian9'      
      - '1.6.11'
      - '1.6'
      - '1'
      - 'latest'
  - repo: nuclio-dashboard
    builderImage: 'nuclio_builder:latest'
    builderArgs: [ 'dashboard' ]
    imageNameFromBuilder: 'local/dashboard:1.6.11'
    tags:
      - '1.6.11-debian9'
      - '1.6-debian9'
      - '1-debian9'
      - '1.6.11'
      - '1.6'
      - '1'
      - 'latest'

cloudbuild:
  enable_parallel: true
